// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"首页","path":"/home","file":"@/pages/Home/index.tsx","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"wangEditor","path":"/WangEditor","file":"@/pages/WangEditor/index.tsx","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"DraftJS","path":"/DraftJS","file":"@/pages/DraftJS/index.tsx","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"SlateJS","path":"/SlateJS","file":"@/pages/SlateJS/index.jsx","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"Quill","path":"/Quill","file":"@/pages/Quill/index.jsx","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"TinyMCE","path":"/TinyMCE","file":"@/pages/TinyMCE/index.jsx","parentId":"ant-design-pro-layout","id":"7"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi/plugin-layout/Layout.tsx","isLayout":true}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__WangEditor__index" */'@/pages/WangEditor/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__DraftJS__index" */'@/pages/DraftJS/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__SlateJS__index" */'@/pages/SlateJS/index.jsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Quill__index" */'@/pages/Quill/index.jsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__TinyMCE__index" */'@/pages/TinyMCE/index.jsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'@/.umi/plugin-layout/Layout.tsx')),
},
  };
}
